### ISSUE TITLE
Що означає колонка "Виявлено" на сторінці візуалізації?

### ISSUE THREAD

**Issue by MatrosSkin** [VasiaPiven/covid19_ua#1]
![Скріншот фрагменту сторінкаи візуалізації](https://i.imgur.com/s4NiczG.png)

Якщо ця колонка означає загальну кількість підтверджених, а не лише активних, тоді чому сумма чисел із колонок правіше відрізняється?

**Comment by VasiaPiven** [comment]
Якщо дивитись на цей поканик на рівні області/країни, то Виявлено – це загальна кількість підтверджених випадків.Якщо дивитись на цей показник на рівні місця госпіталізації – то це кількість підтверджених випадків, які підтвердились у пацієнтів, що перебували за вказаним місцем госпіталізації на момент підтвердження діагнозу. Загальна сума виявлено =хворіє+одужало+померло завжди має співпадати на рівні областей за місцем реєстрації, але може не сходитись на рівні місця госпіталіації, оскільки пацієнти переходять з госпіталізації на самоізоляцію та навпаки протягом лікування. Саме через це розбіжність. В даному випадку, згідно скріншоту, ця розбіжність означає, що у закладі підтвердилось безпосередньо 33 випадки у пацієнтів, що перебували на момент підтвердження в ЗОЗ та ще 4 підтверджених перейшли із самоізоляції в цей заклад і знаходяться там на даний момент. . Надіслано з програми Пошта для Windows 10 Від: MatrosskinНадіслано: 24 квітня 2020 р. о 12:21Кому: VasiaPiven/covid19_uaКопія: SubscribedТема: [VasiaPiven/covid19_ua] Що означає колонка "Виявлено" на сторінці візуалізації? (#1) Якщо ця колонка означає загальну кількість підтверджених, а не лише активних, тоді чому сумма чисел із колонок правіше відрізняється?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MatrosSkin** [comment]
Зрозумів, дякую.
