### ISSUE TITLE
Одруківка в zvit_date

### ISSUE THREAD

**Issue by hp0404** [VasiaPiven/covid19_ua#2]
В датасеті є одруківка в `zvit_date`, де замість `2020-04-28` вказано `2002-04-28`

![image](https://user-images.githubusercontent.com/39014459/80687207-a0936180-8ad2-11ea-97f1-6b282a6e346f.png)

**Comment by VasiaPiven** [comment]
Дякую, виправимо. Надіслано з програми Пошта для Windows 10 Від: hp0404Надіслано: 30 квітня 2020 р. о 11:07Кому: VasiaPiven/covid19_uaКопія: SubscribedТема: [VasiaPiven/covid19_ua] Одруківка в zvit_date (#2) В датасеті є одруківка в zvit_date, де замість 2020-04-28 вказано 2002-04-28—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hp0404** [comment]
Така ж помилка з Рівненською областю сьогодні: 

![image](https://user-images.githubusercontent.com/39014459/82656816-06d05780-9c2d-11ea-9389-1b755bf2b4b5.png)

**Comment by VasiaPiven** [comment]
Дякую. Апдейтнув
